name: ww-ci-39
channels:
  - conda-forge
  - defaults
channel_priority: strict
dependencies:
  - python=3.9
  - pip
  - numpy=1.26
  - pandas=2.2.3
  - numexpr=2.8.7
  - bottleneck=1.3.7
  - matplotlib=3.9.4
  - statsmodels=0.13.2
  - pymc=5.10.4
  - pytensor=2.18.6
  - arviz=0.17.1
  - xarray=2024.7.0
  - xarray-einstats=0.7.0
  - fastprogress=1.0.3
  - python-dateutil=2.8.2
  - pytz=2021.3
  - tzdata=2025.1
  - h5py
  - h5netcdf
  - ipykernel
  - jupyterlab
  - pip:
      - causalimpact==0.2.6

